export const sectorList = [
  {
    id: 1,
    name: "Consumer Good",
  },
  {
    id: 2,
    name: "Other Consumer Services",
  },
  {
    id: 3,
    name: "Telecommunications Equipment",
  },
  {
    id: 4,
    name: "Semiconductors",
  },
  {
    id: 5,
    name: "Building Products",
  },
  {
    id: 6,
    name: "Major Banks",
  },
  {
    id: 7,
    name: "Department/Specialty Retail Stores",
  },
  {
    id: 8,
    name: "Hotels/Resorts",
  },
  {
    id: 9,
    name: "Healthcare",
  },
  {
    id: 10,
    name: "Computer Software",
  },
  {
    id: 11,
    name: "Military/Government/Technical",
  },
  {
    id: 12,
    name: "Other Specialty Stores",
  },
];

export const factorList = [
  {
    id: 1,
    factorName: "Carbon Footprint",
    metrics: [
      {
        id: 1,
        name: "Direct greenhouse gas emissions  (Scope 1)",
        completed: 13,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 2,
        name: "Energy indirect greenhouse gas emissions (Scope 2)",
        completed: 13,
        unit_weights: 2,
        weights: 60,
        status: "active",
      },
      {
        id: 3,
        name: "Total greenhouse gas emissions (Scope 1 & 2)",
        completed: 56,
        unit_weights: 1,
        weights: 20,
        status: "active",
      },
      {
        id: 4,
        name: "Other indirect greenhouse gas emissions (Scope 3)",
        completed: 78,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 5,
        name: "Greenhouse gas intensity (Greenhouse gas emissions/Sales)",
        completed: 98,
        unit_weights: 1,
        weights: 20,
        status: "active",
      },
    ],
  },
  {
    id: 2,
    factorName: "Energy Efficiency",
    metrics: [
      {
        id: 1,
        name: "Direct greenhouse gas emissions  (Scope 1)",
        completed: 13,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 2,
        name: "Energy indirect greenhouse gas emissions (Scope 2)",
        completed: 13,
        unit_weights: 2,
        weights: 60,
        status: "active",
      },
      {
        id: 3,
        name: "Total greenhouse gas emissions (Scope 1 & 2)",
        completed: 56,
        unit_weights: 1,
        weights: 20,
        status: "active",
      },
      {
        id: 4,
        name: "Other indirect greenhouse gas emissions (Scope 3)",
        completed: 78,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 5,
        name: "Greenhouse gas intensity (Greenhouse gas emissions/Sales)",
        completed: 98,
        unit_weights: 1,
        weights: 20,
        status: "active",
      },
    ],
  },
  {
    id: 3,
    factorName: "Environmental Fines",
    metrics: [
      {
        id: 1,
        name: "Direct greenhouse gas emissions  (Scope 1)",
        completed: 13,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 2,
        name: "Energy indirect greenhouse gas emissions (Scope 2)",
        completed: 13,
        unit_weights: 2,
        weights: 50,
        status: "active",
      },
      {
        id: 3,
        name: "Total greenhouse gas emissions (Scope 1 & 2)",
        completed: 56,
        unit_weights: 1,
        weights: 25,
        status: "active",
      },
      {
        id: 4,
        name: "Other indirect greenhouse gas emissions (Scope 3)",
        completed: 78,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 5,
        name: "Greenhouse gas intensity (Greenhouse gas emissions/Sales)",
        completed: 98,
        unit_weights: 1,
        weights: 25,
        status: "active",
      },
    ],
  },
  {
    id: 4,
    factorName: "Training and Education",
    metrics: [
      {
        id: 1,
        name: "Direct greenhouse gas emissions  (Scope 1)",
        completed: 13,
        unit_weights: 2,
        weights: 50,
        status: "active",
      },
      {
        id: 2,
        name: "Energy indirect greenhouse gas emissions (Scope 2)",
        completed: 13,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 3,
        name: "Total greenhouse gas emissions (Scope 1 & 2)",
        completed: 56,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 4,
        name: "Other indirect greenhouse gas emissions (Scope 3)",
        completed: 78,
        unit_weights: 1,
        weights: 25,
        status: "active",
      },
      {
        id: 5,
        name: "Greenhouse gas intensity (Greenhouse gas emissions/Sales)",
        completed: 98,
        unit_weights: 1,
        weights: 25,
        status: "active",
      },
    ],
  },
  {
    id: 5,
    factorName: "Diversity and Equal Opportunity",
    metrics: [
      {
        id: 1,
        name: "Direct greenhouse gas emissions  (Scope 1)",
        completed: 13,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 2,
        name: "Energy indirect greenhouse gas emissions (Scope 2)",
        completed: 13,
        unit_weights: 2,
        weights: 50,
        status: "active",
      },
      {
        id: 3,
        name: "Total greenhouse gas emissions (Scope 1 & 2)",
        completed: 56,
        unit_weights: 2,
        weights: 50,
        status: "active",
      },
      {
        id: 4,
        name: "Other indirect greenhouse gas emissions (Scope 3)",
        completed: 78,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
      {
        id: 5,
        name: "Greenhouse gas intensity (Greenhouse gas emissions/Sales)",
        completed: 98,
        unit_weights: 0,
        weights: 0,
        status: "inactive",
      },
    ],
  },
];
